accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views
from .forms import ResetPasswordForm, PasswordResetSMSForm, LoginForm

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name='logout'),
    # url(r'^password_change/$', auth_views.password_change, name='password_change'),
    # url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', auth_views.password_reset, {
      'template_name': 'accounts/password_reset.html',
      'post_reset_redirect': '/accounts/password_reset/done/',
      'subject_template_name': None,
      'password_reset_form': PasswordResetSMSForm,
    }, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'accounts/password_reset_done.html'}, name='password_reset_done'),
    url(r'^create_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, {
      'post_reset_redirect': '/accounts/create_password/done/',
      'template_name': 'accounts/create_password.html',
      'set_password_form': ResetPasswordForm
    }, name='create_password'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, {
      'post_reset_redirect': '/accounts/reset/done/',
      'template_name': 'accounts/password_reset_confirm.html',
      'set_password_form': ResetPasswordForm
    }, name='password_reset_confirm'),
    url(r'^create_password/done/$', views.password_reset_complete, {
        'template_name': 'accounts/create_password_complete.html'
    }, name='create_password_complete'),
    url(r'^reset/done/$', views.password_reset_complete, {
        'template_name': 'accounts/password_reset_complete.html'
    }, name='password_reset_complete'),
    url(r'^verify/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.verify_email, {}, name='verify_email'),
    url(r'^toggle_status/(?P<pk>\d+)/$', views.toggle_status, name='toggle_status'),
    url(r'^edit_user/(?P<pk>\d+)/$', views.edit_user, name='edit_user'),
    url(r'^create/$', views.create, name='create'),
    url(r'^upload_user_list/$', views.upload_user_list, name='upload_user_list'),
    url(r'^get$', views.get),
    url(r'^recharge$', views.recharge),
    url(r'^create_test_account$', views.create_test_account),
    url(r'^delete_test_account$', views.delete_test_account),
    url(r'^users/$', views.view_users, name='users'),
    url(r'^users/add/$', views.add_user, name='add_user'),
]

billing/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^captive/$', views.captive, name='captive'),
    url(r'^success/$', views.success, name='success'),
    url(r'^resend_mail/$', views.resend_mail, name='resend_mail'),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^packages/', include('packages.urls', namespace="packages")),
    url(r'^pay/', include('payments.urls', namespace='pay')),
    url(r'^admin/', include(admin.site.urls)),
]

search/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

accounts/models.py
#coding=utf-8

from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.utils import timezone

class Nas(models.Model):
    nasname = models.CharField(max_length=128)
    shortname = models.CharField(max_length=32, blank=True, null=True)
    type = models.CharField(max_length=30, blank=True, null=True)
    ports = models.IntegerField(blank=True, null=True)
    secret = models.CharField(max_length=60)
    server = models.CharField(max_length=64, blank=True, null=True)
    community = models.CharField(max_length=50, blank=True, null=True)
    description = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        db_table = 'nas'

class Radacct(models.Model):
    # radacctid = models.BigIntegerField(primary_key=True)
    acctsessionid = models.CharField(max_length=64)
    acctuniqueid = models.CharField(unique=True, max_length=32)
    username = models.CharField(max_length=64)
    groupname = models.CharField(max_length=64)
    realm = models.CharField(max_length=64, blank=True, null=True)
    nasipaddress = models.CharField(max_length=15)
    nasportid = models.CharField(max_length=15, blank=True, null=True)
    nasporttype = models.CharField(max_length=32, blank=True, null=True)
    acctstarttime = models.DateTimeField(blank=True, null=True)
    acctupdatetime = models.DateTimeField(blank=True, null=True)
    acctstoptime = models.DateTimeField(blank=True, null=True)
    acctinterval = models.IntegerField(blank=True, null=True)
    acctsessiontime = models.IntegerField(blank=True, null=True)
    acctauthentic = models.CharField(max_length=32, blank=True, null=True)
    connectinfo_start = models.CharField(max_length=50, blank=True, null=True)
    connectinfo_stop = models.CharField(max_length=50, blank=True, null=True)
    acctinputoctets = models.BigIntegerField(blank=True, null=True)
    acctoutputoctets = models.BigIntegerField(blank=True, null=True)
    calledstationid = models.CharField(max_length=50)
    callingstationid = models.CharField(max_length=50)
    acctterminatecause = models.CharField(max_length=32)
    servicetype = models.CharField(max_length=32, blank=True, null=True)
    framedprotocol = models.CharField(max_length=32, blank=True, null=True)
    framedipaddress = models.CharField(max_length=15)

    class Meta:
        db_table = 'radacct'

class Radgroupcheck(models.Model):
    groupname = models.CharField(max_length=64)
    attribute = models.CharField(max_length=64)
    op = models.CharField(max_length=2)
    value = models.CharField(max_length=253)

    class Meta:
        db_table = 'radgroupcheck'


class Radgroupreply(models.Model):
    groupname = models.CharField(max_length=64)
    attribute = models.CharField(max_length=64)
    op = models.CharField(max_length=2)
    value = models.CharField(max_length=253)

    class Meta:
        db_table = 'radgroupreply'


class Radpostauth(models.Model):
    username = models.CharField(max_length=64)
    pass_field = models.CharField(db_column='pass', max_length=64)  # Field renamed because it was a Python reserved word.
    reply = models.CharField(max_length=32)
    authdate = models.DateTimeField(default=timezone.now)
    message = models.CharField(max_length=255)
    client_mac = models.CharField(max_length=17)

    class Meta:
        db_table = 'radpostauth'


class Radreply(models.Model):
    username = models.CharField(max_length=64)
    attribute = models.CharField(max_length=64)
    op = models.CharField(max_length=2)
    value = models.CharField(max_length=253)

    class Meta:
        db_table = 'radreply'


class Radusergroup(models.Model):
    username = models.CharField(max_length=64)
    groupname = models.CharField(max_length=64)
    priority = models.IntegerField()

    class Meta:
        db_table = 'radusergroup'

class Radcheck(models.Model):
    user = models.OneToOneField(User, null=True)
    username = models.CharField(max_length=100)
    attribute = models.CharField(max_length=64)
    op = models.CharField(max_length=2)
    value = models.CharField(max_length=253)
    is_logged_in = models.BooleanField(default=False)
    data_balance = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    data_usage = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)

    class Meta:
        db_table = 'radcheck'

    def __str__(self):
        return self.username

class GroupAccount(models.Model):
    name = models.CharField(max_length=50)
    max_no_of_users = models.IntegerField(verbose_name="Max. No. of users")
    # For customer support, admins should be able to see these values but unable to edit it.
    data_balance = models.DecimalField(editable=False, default=0.0, max_digits=8, decimal_places=2)
    data_usage = models.DecimalField(editable=False, default=0.0, max_digits=8, decimal_places=2)

    class Meta:
        verbose_name = "Group Account"

    def __str__(self):
        return self.name

    def active_users_count(self):
        """ Return the number of active users in group. """
        return int(User.objects.filter(subscriber__group__name=self.name).filter(is_active=True).count())

    def available_user_slots_count(self):
        """ Call this only if max_user_count_reached returns False. """
        return int(self.max_no_of_users) - self.active_users_count()

    def max_user_count_reached(self):
        """ Check whether group max. no. of users has been reached. """
        return self.active_users_count() == int(self.max_no_of_users)

phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")

class Subscriber(models.Model):
    GHANA = 'GHA'
    NIGERIA = 'NGA'
    IVORY_COAST = 'CIV'
    CONGO_DR = 'COD'
    CAMEROUN = 'CMR'
    ANGOLA = 'AGO'
    GABON = 'GAB'

    COUNTRY_CHOICES = (
        ('', 'Select Country'),
        (GHANA, 'Ghana'),
        (NIGERIA, 'Nigeria'),
        (IVORY_COAST, "Cote d'Ivoire"),
        (CONGO_DR, 'Congo DR'),
        (CAMEROUN, 'Cameroun'),
        (ANGOLA, 'Angola'),
        (GABON, 'Gabon'),
    )

    COUNTRY_CODES_MAP = {
        GHANA: '+233',
        NIGERIA: '+234',
        IVORY_COAST: '+225',
        CONGO_DR: '+243',
        CAMEROUN: '+237',
        ANGOLA: '+244',
        GABON: '+241'
    }

    user = models.OneToOneField(User)
    group = models.ForeignKey(GroupAccount, null=True, blank=True)
    is_group_admin = models.BooleanField(default=False, verbose_name="Group Admin Status",
        help_text="Designates whether this user can create other users in the same group.")
    country = models.CharField(max_length=3, choices=COUNTRY_CHOICES, default=GHANA)
    phone_number = models.CharField(validators=[phone_regex], max_length=15)
    email_verified = models.BooleanField(default=False, help_text="Designates whether this user has confirmed they own specified email address.")
    date_verified = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.user.username

class NetworkParameter(models.Model):
    """
    u'client_ip': [u'10.8.0.78'], 
    u'login_url': [u'https://n110.network-auth.com/splash/login?mauth=MMNsInqn8ksWBR7PgbfBkWG8PawzJm1wi4PE9pDEUdU1qFuHtYczZmRJFJ3dD7AJvl9DRppZnJAZOTA7L3KbzaX4WgwU74t5ibpIJBwHJ-eg5RnL4Hct5hs7i1UIRBH6kbeL9X4hlcFLZKvkaV2mpeP_hX9hxs5jGl_C0N6oWtoQtUjskrMcnBaA&continue_url=http%3A%2F%2Fgoogle.com%2F'], 
    u'continue_url': [u'http://google.com/'], 
    u'ap_tags': [u'office-accra recently-added'], 
    u'ap_mac': [u'00:18:0a:f2:de:20'], 
    u'ap_name': [u'Spectra-HQ-NOC'], 
    u'client_mac': [u'4c:eb:42:ce:6c:3d']}>
    """
    subscriber = models.OneToOneField(Subscriber)
    client_ip = models.CharField(max_length=10)
    login_url = models.CharField(max_length=600)
    continue_url = models.CharField(max_length=50)
    ap_tags = models.CharField(max_length=50)
    ap_mac = models.CharField(max_length=20)
    ap_name = models.CharField(max_length=15)
    client_mac = models.CharField(max_length=20)
    logout_url = models.CharField(max_length=255, default=None, null=True)

class AccessPoint(models.Model):
    PRIVATE = 'PRV'
    PUBLIC = 'PUB'

    STATUS_CHOICES = (
        ('', 'Select Status'),
        (PRIVATE, 'Private'),
        (PUBLIC, 'Public'),
    )

    name = models.CharField(max_length=30, unique=True)
    group = models.ForeignKey(GroupAccount, null=True, blank=True)
    mac_address = models.CharField(max_length=17, unique=True)
    status = models.CharField(max_length=3, choices=STATUS_CHOICES, default=PRIVATE)

    class Meta:
        verbose_name = "Access Point"

    def allows(self, user):
        if self.status == 'PUB':
            return True # AP is public, all users can connect
        else:
            if not isinstance(user, User):
                return False
            else:
                if user.subscriber.group is not None and self.group is not None: # This ensures we return False even if AP doesn't belong to a group
                    if user.subscriber.group == self.group:
                        return True # Users in same group as AP can connect
                    else:
                        return False # Users in other groups can not connect to this AP
                return False # AP is private, only users who belong to AP group can connect

    def __str__(self):
        return self.name

class RechargeAndUsage(models.Model):
    RECHARGE = 'REC'
    USAGE = 'USG'

    ACTION_CHOICES = (
        ('', 'Select Action'),
        (RECHARGE, 'Recharge'),
        (USAGE, 'Usage'),
    )

    radcheck = models.ForeignKey(Radcheck)
    amount = models.DecimalField(max_digits=8, decimal_places=2) # Recharges are positive values, usages are negative values
    balance = models.DecimalField(max_digits=8, decimal_places=2) # Stores balance after every recharge or usage activity, we have to fetch last activity's balance to compute this.

accounts/templates/accounts/_table_header.html
<thead>
  <tr>
    <th>Package</th>
    <th>Purchased</th>
    <th>Starts</th>
    <th>Expires</th>
  </tr>
</thead>

accounts/templates/accounts/group_member_welcome_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because an administrator created an account for you at {{ site_name }}.{% endblocktrans %}

{% trans "You may click on the link below to set your password:" %}
{% block set_password_link %}

      {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
                  
{% endblock %}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team.{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block nav_items %}
  <ul class="nav navbar-nav">
  {% with urlname=request.resolver_match.url_name %}
    <li {% if urlname == 'index' %}class="active"{% endif %}>
      <a href="{% url 'index' %}">
        <span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span>
        Dashboard 
        {% if urlname == 'index' %}
          <span class="sr-only">(current)</span></a>
        {% endif %}
      </a>
    </li>
    {% if user.subscriber.group == None %}
      <li {% if urlname == 'buy' %}class="active"{% endif %}>
        <a href="{% url 'packages:buy' %}">
          <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
          Buy Package 
          {% if urlname == 'buy' %}
            <span class="sr-only">(current)</span></a>
          {% endif %}
        </a>
      </li>
    {% elif user.subscriber.is_group_admin %}
      <li {% if urlname == 'users' %}class="active"{% endif %}>
        <a href="{% url 'accounts:users' %}">
          <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
          View Users 
          {% if urlname == 'users' %}
            <span class="sr-only">(current)</span></a>
          {% endif %}
        </a>
      </li>
      <li {% if urlname == 'add_user' %}class="active"{% endif %}>
        <a href="{% url 'accounts:add_user' %}">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
          Add User 
          {% if urlname == 'add_user' %}
            <span class="sr-only">(current)</span></a>
          {% endif %}
        </a>
      </li>
      <li {% if urlname == 'upload_user_list' %}class="active"{% endif %}>
        <a href="{% url 'accounts:upload_user_list' %}">
          <span class="glyphicon glyphicon-upload" aria-hidden="true"></span>
          Upload User List 
          {% if urlname == 'upload_user_list' %}
            <span class="sr-only">(current)</span></a>
          {% endif %}
        </a>
      </li>
    {% endif %}
  {% endwith %}
  </ul>

  <ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          {% if user.get_full_name %}{{ user.get_full_name }}{% else %}{{ user.username }}{% endif %} <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a href="{% url 'accounts:logout' %}">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              Logout
            </a>
          </li>
        </ul>
      </li>
    {% else %}
      <li><a href="{% url 'login' %}">Login</a></li>
    {% endif %}
  </ul>
{% endblock %}







{% block app_body %}
<div class="row main">
  <div class="welcome">
    <div class="col-lg-9">
      <!--- {% if not verified %}
        <div class="panel panel-default">
          <div class="panel-body">
            Welcome {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}. Please verify your account. <a class="btn btn-primary btn-xs pull-right" href="{% url 'resend_mail' %}">Resend verification mail</a>
          </div>
        </div>
      {% endif %} -->

      {% if active_subscription %}
        <div class="page-header">
          <h2>Active Subscription</h2>
        </div>
        <table class="table table-condensed table-striped">
          {% include 'accounts/_table_header.html' %}
          <tbody>
            <tr>
              <td>{{ active_subscription.package }}</td>
              <td>{{ active_subscription.purchase_date }}</td>
              <td>{{ active_subscription.start }}</td>
              <td>{{ active_subscription.stop }}</td>
            </tr>
          </tbody>
        </table>
      {% else %}
        <p>
          You do not have an active subscription. 
          {% with balance=user.radcheck.rechargeandusage_set.all.0.balance %}
            {% if balance %}
              {% if user.subscriber.group == None %}
                <strong><a href="{% url 'packages:buy' %}">Buy Package</a></strong>.
              {% endif %}
            {% endif %}
          {% endwith %}
        </p>
      {% endif %}

      {% if unused_subscriptions %}
        <div class="page-header">
          <h2>Unused Subscriptions</h2>
        </div>
        <table class="table table-condensed table-striped">
          {% include 'accounts/_table_header.html' %}
          <tbody>
            {% for s in unused_subscriptions %}
              <tr>
                <td>{{ s.package }}</td>
                <td>{{ s.purchase_date }}</td>
                <td>{{ s.start }}</td>
                <td>{{ s.stop }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      {% endif %}

      {% if expired_subscriptions %}
        <div class="page-header">
          <h2>Package Subscription History</h2>
        </div>
        <table class="table table-condensed table-striped">
          {% include 'accounts/_table_header.html' %}
          <tbody>
            {% for s in expired_subscriptions %}
              <tr>
                <td>{{ s.package }}</td>
                <td>{{ s.purchase_date }}</td>
                <td>{{ s.start }}</td>
                <td>{{ s.stop }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      {% endif %}
    </div>
    <div class="col-lg-3">
      <div class="balance-pane">
        Data Balance<br>
        <span>
          {% if user.subscriber.group == None %}
            {% if subscription_is_unlimited %}
              Unlimited
            {% else %}
              {{ user.radcheck.data_balance }} GB
            {% endif %}
          {% else %}
            {% if subscription_is_unlimited %}
              Unlimited
            {% else %}
              {{ user.subscriber.group.data_balance }} GB
            {% endif %}
          {% endif %}
        </span>
      </div>
      {% if user.subscriber.group == None %}
        <div class="cash balance-pane">
          Cash Balance<br>
          <span>
            {% with balance=user.radcheck.rechargeandusage_set.all.0.balance %}
              {% if balance %}
                {{ user.radcheck.rechargeandusage_set.all.0.balance }}
              {% else %}
                0
              {% endif %} GHS
            {% endwith %}
          </span>
        </div>
      {% endif %}
      {% if active_subscription %}
        {% if not logout_url and captive_url %}
  	      <a class="btn btn-primary end-session" role="button" href="{{ captive_url }}">Log In To Browse</a>
        {% endif %}
      {% endif %}
      {% if logout_url %}
	      <a class="btn btn-primary end-session" role="button" href="{{ logout_url }}">End Browsing Session</a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Log In To Manage Account{% endblock %}

{% block app_body %}
<div class="row main">
  <form method="post" action="{{ login_url }}" class="login-form">
    <fieldset>
      <div class="page-header">
        <h2>{% block form_header %}Manage Account{% endblock %}</h2>
      </div>
      {% csrf_token %}
      {{ form.non_field_errors }}

      <ul class="errorlist nonfield"><li>{{ error_message }}</li></ul>
      <input type="hidden" name="success_url" value="{{ success_url }}">

      <div class="form-group">
        {% if form.username %}
          {{ form.username.errors }}
          {{ form.username.label_tag }}
          {{ form.username }}
        {% else %}
          {{ form.ga_user.errors }}
          {{ form.ga_user.label_tag }}
          {{ form.ga_user }}
        {% endif %}
      </div>

      <div class="form-group">
        {% if form.password %}
          {{ form.password.errors }}
          {{ form.password.label_tag }}
          {{ form.password }}
        {% else %}
          {{ form.ga_pass.errors }}
          {{ form.ga_pass.label_tag }}
          {{ form.ga_pass }}
        {% endif %}
      </div>

      <button type="submit" class="btn btn-primary">Log In</button>
      
      {% block links %}
      <p>
        <a href="{% url 'accounts:password_reset' %}">Forgot Password?</a><br>
      </p>
      {% endblock %}
    </fieldset>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Password Reset{% endblock %}

{% block app_body %}
<div class="row main">
    <div class="col-sm-12">
        <div class="well">
            <h4>{% block header %}Password reset complete{% endblock %}</h4>
            <p>
                {% block action_message %}Your password has been reset.{% endblock %}
                You may <a href="{% url 'accounts:login' %}">manage your account</a> 
                {% if not captive_url %}
                    or reconnect to the WiFi network to log in with your new password.
                {% else %}
                    <a href="{{ captive_url }}">log in to browse</a> now.
                {% endif %}
            </p>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/user_list.html
{% extends 'accounts/index.html' %}

{% block title %}{{ user.subscriber.group.name }} Users{% endblock %}

{% block app_body %}
<div class="row">
  <div class="col-md-6">
    {% block search_form %}
    <form class="search-form" action="{% url 'search:index' %}" method="get">
      <div class="input-group">
        <input type="text" class="form-control" name="q" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </button>
        </span>
      </div>
    </form>
    {% endblock %}
  </div>
  <div class="col-md-6 paginate-by">
    {% block paginate_by %}
    <ul class="pagination">
      <li>
        <span>Show up to</span>
      </li>
      {% with row_count=request.GET.paginate_by %}
      <li {% if row_count == '5' %}class="active"{% endif %}><a href="?paginate_by=5">5</a></li>
      <li {% if row_count == '10' %}class="active"{% endif %}><a href="?paginate_by=10">10</a></li>
      <li {% if row_count == '20' %}class="active"{% endif %}><a href="?paginate_by=20">20</a></li>
      <li {% if row_count == '25' %}class="active"{% endif %}><a href="?paginate_by=25">25</a></li>
      {% endwith %}
      <li>
        <span>rows</span>
      </li>
    </ul>
    {% endblock %}
  </div>
</div>

<div class="row">
  {% if users %}
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">User Name</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Date Created</th>
          <th scope="col">Action</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <td>{{ user.pk }}</td>
          <td><a href="{% url 'accounts:edit_user' pk=user.pk %}">{{ user.username }}</a></td>
          <td>{{ user.first_name }}</td>
          <td>{{ user.last_name }}</td>
          <td>{{ user.date_joined }}</td>
          <td>
            <form action="{% url 'accounts:toggle_status' pk=user.pk %}" method="post">
              {% csrf_token %}
              {% if user.is_active %}
                <button type="submit" class="btn btn-xs btn-danger">Deactivate</button>
              {% else %}
                <button type="submit" class="btn btn-xs btn-primary">Activate</button>
              {% endif %}
            </form>
          </td>
          <td>
            {% if user.radcheck.is_logged_in %}
              <span title="Online" class="glyphicon glyphicon-ok-sign indicator indicator-online" aria-hidden="true"></span>
            {% else %}
              <span title="Offline" class="glyphicon glyphicon-ok-sign indicator indicator-offline" aria-hidden="true"></span>
            {% endif %}
          </td>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="col-lg-12">
      {% block no_results %}
        <div class="panel panel-default">
          <div class="panel-body">
            There are no users in this group.
            <a class="pull-right btn btn-primary btn-xs" href="{% url 'accounts:add_user' %}">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
              Add User
            </a>
            <a class="pull-right btn btn-primary btn-xs upload-btn" href="{% url 'accounts:upload_user_list' %}">
              <span class="glyphicon glyphicon-upload" aria-hidden="true"></span>
              Upload User List
            </a>
          </div>
        </div>
      {% endblock %}
    </div>
  {% endif %}
</div>

<nav>
  <ul class="pager">
  {% if users.has_previous %}
    <li class="previous">
      <a href="?page={{ users.previous_page_number }}&paginate_by={{ paginate_by }}">
        <span aria-hidden="true">&larr;</span> Previous
      </a>
    </li>
  {% endif %}
  {% if users.has_next %}
    <li class="next">
      <a href="?page={{ users.next_page_number }}&paginate_by={{ paginate_by }}">
        Next <span aria-hidden="true">&rarr;</span>
      </a>
    </li>
  {% endif %}
  </ul>
</nav>
{% endblock %}

accounts/templates/accounts/verification_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you created an account at {{ site_name }}.{% endblocktrans %}

{% trans "Please click on the link below to verify your email:" %}
{% block verify_link %}

      {{ protocol }}://{{ domain }}{% url 'accounts:verify_email' uidb64=uid token=token %}
                  
{% endblock %}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team.{% endblocktrans %}

{% endautoescape %}