accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views
from .forms import ResetPasswordForm, PasswordResetSMSForm, LoginForm

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name='logout'),
    # url(r'^password_change/$', auth_views.password_change, name='password_change'),
    # url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', auth_views.password_reset, {
      'template_name': 'accounts/password_reset.html',
      'post_reset_redirect': '/accounts/password_reset/done/',
      'subject_template_name': None,
      'password_reset_form': PasswordResetSMSForm,
    }, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'accounts/password_reset_done.html'}, name='password_reset_done'),
    url(r'^create_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, {
      'post_reset_redirect': '/accounts/create_password/done/',
      'template_name': 'accounts/create_password.html',
      'set_password_form': ResetPasswordForm
    }, name='create_password'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, {
      'post_reset_redirect': '/accounts/reset/done/',
      'template_name': 'accounts/password_reset_confirm.html',
      'set_password_form': ResetPasswordForm
    }, name='password_reset_confirm'),
    url(r'^create_password/done/$', views.password_reset_complete, {
        'template_name': 'accounts/create_password_complete.html'
    }, name='create_password_complete'),
    url(r'^reset/done/$', views.password_reset_complete, {
        'template_name': 'accounts/password_reset_complete.html'
    }, name='password_reset_complete'),
    url(r'^verify/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.verify_email, {}, name='verify_email'),
    url(r'^toggle_status/(?P<pk>\d+)/$', views.toggle_status, name='toggle_status'),
    url(r'^edit_user/(?P<pk>\d+)/$', views.edit_user, name='edit_user'),
    url(r'^create/$', views.create, name='create'),
    url(r'^upload_user_list/$', views.upload_user_list, name='upload_user_list'),
    url(r'^get$', views.get),
    url(r'^recharge$', views.recharge),
    url(r'^create_test_account$', views.create_test_account),
    url(r'^delete_test_account$', views.delete_test_account),
    url(r'^users/$', views.view_users, name='users'),
    url(r'^users/add/$', views.add_user, name='add_user'),
]

billing/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^captive/$', views.captive, name='captive'),
    url(r'^success/$', views.success, name='success'),
    url(r'^resend_mail/$', views.resend_mail, name='resend_mail'),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^packages/', include('packages.urls', namespace="packages")),
    url(r'^pay/', include('payments.urls', namespace='pay')),
    url(r'^admin/', include(admin.site.urls)),
]

search/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

templates/base.html
<!DOCTYPE HTML>
<html>
  <head>
    <title>CloudBiller &mdash; {% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/example.wink.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/hideShowPassword.min.js' %}"></script>
    <script>
      jQuery(document).ready(function($) {
        $("#id_password").hidePassword(true);
      });
    </script>
  </head>

  <body>
    <nav class="navbar navbar-default header">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#billing-navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">CloudBiller Self Care</a>
        </div>

        <div class="collapse navbar-collapse" id="billing-navbar-collapse">
        {% block nav_items %}
        {% endblock %}
        </div>

      </div>
    </nav>

    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message | safe }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <div class="container-fluid">
      {% block app_body %}
      {% endblock %}
    </div>

    <footer class="footer">
      <div class="col-md-6">
        <p>&copy; 2016 Spectra Wireless.</p>
      </div>
      <div class="col-md-6">
        <p class="pull-right">Customer Care Line: <strong>055 324 2528</strong></p>
      </div>
    </footer>
    
    <script>
      $('form').submit(function() {
        var btn = $(this).find('.btn');
        btn.text('Wait...');
        btn.prop('disabled', true);
      });
    </script>

  </body>
</html>

templates/captive.html
{% extends 'accounts/login.html' %}

{% block title %}Captive Portal{% endblock %}

{% block form_header %}Log In{% endblock %}

{% block links %}
<p>
  <a href="{% url 'accounts:password_reset' %}">Forgot Password?</a> &#8226; 
  <a href="{% url 'accounts:create' %}">Create Account</a> &#8226; 
  <a href="{% url 'accounts:login' %}">Manage Account</a>
</p>
{% endblock %}